name: proto_madera_front
version: 1.0.0
description: >-
  This is the pubspec of the MADERA mobile app for LesCodeursEnBois graduation project. Enjoy.
repository: https://github.com/RcDevRIL/proto_madera_front
documentation: https://github.com/RcDevRIL/proto_madera_front/blob/master/README.md

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.22.6
  logger: ^0.7.0+2
  provider: ^3.2.0
  http: ^0.12.0+4
  crypto: ^2.1.3
  sqflite: ^1.2.0
  moor_flutter: ^2.0.0
  json_serializable: ^3.2.3
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1

dev_dependencies:
  moor_generator: ^2.2.0
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true 
  image_path: "assets/img/icons/icon-madera.png"

flutter:

  uses-material-design: true

  assets:
   - assets/img/logo-madera.png
   - assets/img/madera.JPG
   - assets/img/icons/off.png
   - assets/img/echeancier.PNG
   - assets/img/suiviDevis.jpg
   - assets/img/creationDevis.jpg
